package de.teampb.adf.demos.doag.cloud.model.queries.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 18 12:14:22 CET 2023
// ---------------------------------------------------------------------
public interface EmployeesView extends ViewObject {
    void setSalaryToMaxSalaryForEmployeesOfManager(Integer managerId);

    void forceValidationExceptionOnEntity(Integer managerId);
}

