package de.teampb.adf.demos.doag.cloud.model.endpoints.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 17 12:28:30 CET 2023
// ---------------------------------------------------------------------
public interface HREndpoint extends ApplicationModule {
    void setSalaryToMaxSalaryForEmployeesOfManager(Integer managerId);
}

