package de.teampb.adf.demos.doag.cloud.model.queries;

import de.teampb.adf.demos.doag.cloud.model.endpoints.HREndpointImpl;
import de.teampb.adf.demos.doag.cloud.model.entities.EmployeesImpl;

import de.teampb.adf.demos.doag.cloud.model.queries.common.EmployeesView;

import oracle.jbo.RowIterator;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 17 12:21:46 CET 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesViewImpl extends ViewObjectImpl implements EmployeesView {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesViewImpl() {
    }
    
    public void setSalaryToMaxSalaryForEmployeesOfManager(Integer managerId){
        HREndpointImpl applicationModule = (HREndpointImpl)this.getApplicationModule();
        EmployeesViewImpl byId = applicationModule.getEmployeeById();
        byId.ensureVariableManager().setVariableValue("paramEmployeeId", managerId);
        byId.executeQuery();
        EmployeesViewRowImpl manager = (EmployeesViewRowImpl)byId.first();

        RowIterator rowIterator = manager.getEmployeesView();
        rowIterator.reset();
        
        while(rowIterator.hasNext()){
            ViewRowImpl row =  (ViewRowImpl)rowIterator.next();
            EmployeesImpl emp = (EmployeesImpl) row.getEntity(0);
            emp.setSalaryToMax();
            emp.validate();
        }
        this.getDBTransaction().commit();
        
    }
}

