package de.teampb.adf.demos.doag.cloud.model.queries;

import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 17 10:31:40 CET 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class JobsViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_JOBS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        JobId,
        JobTitle,
        MinSalary,
        MaxSalary,
        JobAugmentedTitle,
        EmployeesView;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int JOBID = AttributesEnum.JobId.index();
    public static final int JOBTITLE = AttributesEnum.JobTitle.index();
    public static final int MINSALARY = AttributesEnum.MinSalary.index();
    public static final int MAXSALARY = AttributesEnum.MaxSalary.index();
    public static final int JOBAUGMENTEDTITLE = AttributesEnum.JobAugmentedTitle.index();
    public static final int EMPLOYEESVIEW = AttributesEnum.EmployeesView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public JobsViewRowImpl() {
    }

    /**
     * Gets Jobs entity object.
     * @return the Jobs
     */
    public EntityImpl getJobs() {
        return (EntityImpl) getEntity(ENTITY_JOBS);
    }

    /**
     * Gets the attribute value for JOB_ID using the alias name JobId.
     * @return the JOB_ID
     */
    public String getJobId() {
        return (String) getAttributeInternal(JOBID);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_ID using the alias name JobId.
     * @param value value to set the JOB_ID
     */
    public void setJobId(String value) {
        setAttributeInternal(JOBID, value);
    }

    /**
     * Gets the attribute value for JOB_TITLE using the alias name JobTitle.
     * @return the JOB_TITLE
     */
    public String getJobTitle() {
        return (String) getAttributeInternal(JOBTITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_TITLE using the alias name JobTitle.
     * @param value value to set the JOB_TITLE
     */
    public void setJobTitle(String value) {
        setAttributeInternal(JOBTITLE, value);
    }

    /**
     * Gets the attribute value for MIN_SALARY using the alias name MinSalary.
     * @return the MIN_SALARY
     */
    public Integer getMinSalary() {
        return (Integer) getAttributeInternal(MINSALARY);
    }

    /**
     * Sets <code>value</code> as attribute value for MIN_SALARY using the alias name MinSalary.
     * @param value value to set the MIN_SALARY
     */
    public void setMinSalary(Integer value) {
        setAttributeInternal(MINSALARY, value);
    }

    /**
     * Gets the attribute value for MAX_SALARY using the alias name MaxSalary.
     * @return the MAX_SALARY
     */
    public Integer getMaxSalary() {
        return (Integer) getAttributeInternal(MAXSALARY);
    }

    /**
     * Sets <code>value</code> as attribute value for MAX_SALARY using the alias name MaxSalary.
     * @param value value to set the MAX_SALARY
     */
    public void setMaxSalary(Integer value) {
        setAttributeInternal(MAXSALARY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute JobAugmentedTitle.
     * @return the JobAugmentedTitle
     */
    public String getJobAugmentedTitle() {
        return (String) getAttributeInternal(JOBAUGMENTEDTITLE);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EmployeesView.
     */
    public RowIterator getEmployeesView() {
        return (RowIterator) getAttributeInternal(EMPLOYEESVIEW);
    }
}

