apiVersion: apps/v1
kind: Deployment
metadata:
  name: wls-doag-db
  namespace: wls-doag
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dev
      app.kubernetes.io/name: wls-doag-db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: dev
        app.kubernetes.io/name: wls-doag-db
    spec:
      containers:
      - env:
        - name: ORACLE_PWD
          value: oracle
        image: container-registry.oracle.com/database/free
        imagePullPolicy: IfNotPresent
        name: oracle-db
        ports:
        - containerPort: 1521
          name: tns
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
            ephemeral-storage: 4Gi
          requests:
            cpu: 200m
            ephemeral-storage: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: wls-doag-db
  namespace: wls-doag
spec:
  ports:
  - name: tns
    port: 1521
    protocol: TCP
    targetPort: 1521
  selector:
    app.kubernetes.io/instance: dev
    app.kubernetes.io/name: wls-doag-db
  sessionAffinity: None
  type: ClusterIP

