# Copyright (c) 2018, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: domain1-wls-doag-pv
  namespace: wls-doag
  labels:
    weblogic.domainUID: domain1
spec:
  storageClassName: domain1-wls-doag-storage-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  # Valid values are Retain, Delete or Recycle
  persistentVolumeReclaimPolicy: Retain
  hostPath:
  # nfs:
    # server: %SAMPLE_STORAGE_NFS_SERVER%
    path: "/home/opc/wls-domain-volume"


---    
# Copyright (c) 2018, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: domain1-wls-doag-pvc
  namespace: wls-doag
  labels:
    weblogic.domainUID: domain1
spec:
  storageClassName: domain1-wls-doag-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
