package de.teampb.adf.demos.doag.cloud.model.endpoints;

import de.teampb.adf.demos.doag.cloud.model.entities.EmployeesImpl;
import de.teampb.adf.demos.doag.cloud.model.queries.EmployeesViewImpl;

import de.teampb.adf.demos.doag.cloud.model.queries.EmployeesViewRowImpl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 17 12:14:39 CET 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HREndpointImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HREndpointImpl() {
    }

    /**
     * Container's getter for AllDepartments.
     * @return AllDepartments
     */
    public ViewObjectImpl getAllDepartments() {
        return (ViewObjectImpl) findViewObject("AllDepartments");
    }

    /**
     * Container's getter for AllEmployees.
     * @return AllEmployees
     */
    public EmployeesViewImpl getAllEmployees() {
        return (EmployeesViewImpl) findViewObject("AllEmployees");
    }

    /**
     * Container's getter for EmployeesUnderManager.
     * @return EmployeesUnderManager
     */
    public EmployeesViewImpl getEmployeesUnderManager() {
        return (EmployeesViewImpl) findViewObject("EmployeesUnderManager");
    }

    /**
     * Container's getter for DepartmentsWhereEmpIsManager.
     * @return DepartmentsWhereEmpIsManager
     */
    public ViewObjectImpl getDepartmentsWhereEmpIsManager() {
        return (ViewObjectImpl) findViewObject("DepartmentsWhereEmpIsManager");
    }

    /**
     * Container's getter for EmployeesByDepartment.
     * @return EmployeesByDepartment
     */
    public EmployeesViewImpl getEmployeesByDepartment() {
        return (EmployeesViewImpl) findViewObject("EmployeesByDepartment");
    }

    /**
     * Container's getter for JobsView1.
     * @return JobsView1
     */
    public ViewObjectImpl getJobsView1() {
        return (ViewObjectImpl) findViewObject("JobsView1");
    }

    /**
     * Container's getter for EmployeesByManagerLink.
     * @return EmployeesByManagerLink
     */
    public ViewLinkImpl getEmployeesByManagerLink() {
        return (ViewLinkImpl) findViewLink("EmployeesByManagerLink");
    }

    /**
     * Container's getter for DepartmentsByManagerLink.
     * @return DepartmentsByManagerLink
     */
    public ViewLinkImpl getDepartmentsByManagerLink() {
        return (ViewLinkImpl) findViewLink("DepartmentsByManagerLink");
    }

    /**
     * Container's getter for EmployeesByDepartmentLink.
     * @return EmployeesByDepartmentLink
     */
    public ViewLinkImpl getEmployeesByDepartmentLink() {
        return (ViewLinkImpl) findViewLink("EmployeesByDepartmentLink");
    }

    /**
     * Container's getter for EmployeesView1.
     * @return EmployeesView1
     */
    public EmployeesViewImpl getEmployeeById() {
        return (EmployeesViewImpl) findViewObject("EmployeeById");
    }

    /**
     * Container's getter for EmployeesView1.
     * @return EmployeesView1
     */
    public EmployeesViewImpl getEmployeesUnderSingleEmployee() {
        return (EmployeesViewImpl) findViewObject("EmployeesUnderSingleEmployee");
    }

    /**
     * Container's getter for EmpManagerFkLink1.
     * @return EmpManagerFkLink1
     */
    public ViewLinkImpl getEmpManagerFkLink1() {
        return (ViewLinkImpl) findViewLink("EmpManagerFkLink1");
    }
}

